### Register User
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "email": "test7@gmail.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "123456"
}

###

### Login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "test7@gmail.com",
  "password": "123456"
}

###

### Create Project
POST http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzQXQiOjE3NTQ3MjU2ODYsInVzZXJJRCI6IjExIn0.bWn4XsMWii9isxLCEC8BnuSUEoSKwRzOdpf8siBEvQ4
Content-Type: application/json

{
  "name": "My New Project 3"
}

###

### Get Project by ID
GET http://localhost:8080/api/v1/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzQXQiOjE3NTQ3MjU2ODYsInVzZXJJRCI6IjExIn0.bWn4XsMWii9isxLCEC8BnuSUEoSKwRzOdpf8siBEvQ4

###

### Delete Project
DELETE http://localhost:8080/api/v1/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzQXQiOjE3NTQ3MjQ4ODksInVzZXJJRCI6IjcifQ.B8VwwN8BRLE4ojOlcAVv6fW06TxhbfPB2yBNMIlpM0c

###
